### ISSUE TITLE
Update annotations: only recreate modified annotations (instead of all)

### ISSUE THREAD

**Issue by wimallegaert** [ices-eg/SmartDots#150]
Issue: 
- Country coordinators can see all annotions. When they create a annotation themselves all existings annotations will be recreated. 
- The ICES We api does not allow to delete (approved) annotations from other readers. (What's a secure approach)

Proposal: Only (re)create modified annotations.

**Comment by wimallegaert** [comment]
Feedback ILVO: functionality in SmartDots is already like wished: only modified annotations will be send to the Web API. Existing annotation, which were not modified will not be posted to the web api.
To resolve the issue, only a modification in the Web API is needed.

**Comment by kevinatilvo** [comment]
> Feedback ILVO: functionality in SmartDots is already like wished: only modified annotations will be send to the Web API. Existing annotation, which were not modified will not be posted to the web api.
> To resolve the issue, only a modification in the Web API is needed.

This is indeed an Exception that is thrown by the Web API, the code in the "updateannotations" end point will need some modification.

I have removed the Software label and have added the Web API label.

**Comment by JCoadDavies** [comment]
@wimallegaert @kevinatilvo @cmspinto 
Can this be closed?

**Comment by wimallegaert** [comment]
@cmspinto: can you have a look at this Carlos? The software sends only the new / modified annotations to the Web API. According to the remark of @kevinatilvo the "updateannotations" end point need some modification in the Web API.

**Comment by wimallegaert** [comment]
> @wimallegaert @kevinatilvo @cmspinto
> Can this be closed?

@cmspinto: can you have a look at this Carlos? The software sends only the new / modified annotations to the Web API. According to the remark of @kevinatilvo the "updateannotations" end point need some modification in the Web API.

**Comment by cmspinto** [comment]
I can make this changes but need to agree with @kevinatilvo.
The current API receives a list of Annotations to change, it then deletes these annotations and creates them again:
![image](https://user-images.githubusercontent.com/8705477/187616381-8637b09c-27be-4450-84fc-2904319484e4.png)

Issue is that the Event Coordinator or the Event Delegates have access to all the annotations of the readers. 
When the Coordinator or the Delegates creates or changes one annotation, then the software will try to post all the annotations that the user can see, so all his annotations but also the annotations from other users. The software does this by default I guess because it does not know what annotations have changed so it posts all the annotations.

This is where the webAPI put a limit, that is **for security and authenticity**, the users are not able to **create or change annotations that are from other users**

Would the software be able to post only Annotations from the current user? 

Hope this makes sense.

**Comment by wimallegaert** [comment]
@cmspinto: the software sends only the modified annotations to the Web API (UpdateAnnotations).
