### ISSUE TITLE
Stress test

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#212]
We need  a stress test to now how many can take part in an event without slowing the system

**Comment by cmspinto** [comment]
[SmartDots-stresstest-2021-03-08-17-49-53.txt](https://github.com/ices-eg/SmartDots/files/6129741/SmartDots-stresstest-2021-03-08-17-49-53.txt)
[SmartDots-stresstest-2021-03-08-17-51-27.txt](https://github.com/ices-eg/SmartDots/files/6129742/SmartDots-stresstest-2021-03-08-17-51-27.txt)
[SmartDots-stresstest-2021-03-08-17-44-49.txt](https://github.com/ices-eg/SmartDots/files/6129743/SmartDots-stresstest-2021-03-08-17-44-49.txt)

In the attachments you can see the results from the stress test.
I did 3 tests:
-	Same api calls are done 100 times asynchronous (all at once), the result is when we received all answers
-	Same api calls are done 100 times synchronous (one by one), the result is when we received all answers
-	A normal test with just 1 call per request

I see no issues in the web api implementations. The list of events takes the longest, because there is a lot of info to query.
It could still be useful to take a look where api call execution times could be reduced.

Another factor that could slow down the system is the network infrastructure and the size of images to download.
The image I tested on is very small in filesize and loads very quick.

**Comment by JCoadDavies** [comment]
From WGSMART meeting 11/05/21

WebApi should be working fine.
A small setting in the server was changed which has improved the system.
If we begin to upload very large images to SmartDots then the loading time in the software will be extended and could cause delays when viewing the images.

Kevin has created a tool which can run these tests quickly so this should be done 2/3 per year.

**Comment by JaneGodiksen** [comment]
I think a stress test makes sense when we have some major changes that can affect the speed, but not necessarily to do it regularly. And I think twice a year as suggested in the email seems to be too much and too much effort to put into it. But if it is easily done, then this could be a simple task for one of the members of WGSMART to do - and sometimes it is easier to get things done if it is planned regularly.

**Comment by JCoadDavies** [comment]
Needs to be tested by a developer - Kevin and Wim have a tool to do this. To be done twice a year
