### ISSUE TITLE
Fecundity and Atresia

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/SmartDots#219]

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/98794173-05782e80-2409-11eb-908c-7842ac94cfad.png)

**Comment by cmspinto** [comment]
The event coordinator set the threshold for the minimum circle (in yellow in the image).

![image](https://user-images.githubusercontent.com/8705477/98795413-7bc96080-240a-11eb-9692-4aee6a12037b.png)


The output for this images is:
- the ones that need to be deleted 
- the ones that need to be added

**Comment by cmspinto** [comment]
Histology screening

![image](https://user-images.githubusercontent.com/8705477/98797368-bf24ce80-240c-11eb-9300-5978e552cdac.png)


The coordinator choose the distinct available markers for that event and those will be the ones available.
The final output is the summary of markers used by the user in the image.

**Comment by cmspinto** [comment]
When the event coordinator uploads the samples it will have define for each sample or image what type of marker it needs (Fecundity/Atresia/Histology screening)

**Comment by CindyvanDamme** [comment]
For the fecundity we also discussed:
In case the automated marking is not correct. Can we add a different marker for 'one that needs to be edited'. 

Question: Can this marker for 'one that needs to be edited' be set in a way that if this marker is used a comment is required why this one needs to be edited? This would then be needed for al the cells marked as 'one that needs to be edited'. Maybe a drop-down list would be needed for this?

**Comment by CindyvanDamme** [comment]
Need to provide a list with stages for Atresia. (Or is this already in the ICES vocab through the fecundity and atresia database preparation?)

Need to provide a list with cells to mark for Histology screening

**Comment by cmspinto** [comment]
For a clear evaluation of the issue and priority it would help WGSMART to know:
o	A short description on what specifically the module of “Fecundity and Atresia” is for and how will that contribute to improving the quality of data?
o	Are the results used in the stock assessment process?
o	Do you know what groups deal with Fecundity and Atresia? (this is for possible linkage with WGBIOP) 
o	When would the module need to be developed (have the vague idea that next event was by November 2021 but was not 100% sure)
o	Could WGSMART get information on the WK that they want to use it for?  (I think it was for a specific species but maybe it was related to a project or a stock assessment group).

**Comment by CindyvanDamme** [comment]
For a clear evaluation of the issue and priority it would help WGSMART to know:
o	A short description on what specifically the module of “Fecundity and Atresia” is for and how will that contribute to improving the quality of data?
For egg production methods (EPM) to estimate spawning stock biomass (SSB) it is necessary to know the realised/batch fecundity. Egg production is divided by fecundity to calculate SSB. For mackerel, horse mackerel, anchovy and sardine EPM indices are used in the assessment. To estimate realised fecundity we first need to estimate potential or batch fecundity. This can only be estimated for fish close to or during spawning. Therefor ovaries are first screened histologically to get the true maturity stage (analyses 1). Then (batch) fecundity is estimated from whole mounts (analyses 2). During the spawning season fecundity is regulated by atresia. Thus atresia is estimated from histological samples (step 3). Lastly the spawning fraction, actual number of females that spawn in a day is estimated from histological slides by staging Post Ovulatory Follicles (POFs; step 4). We have been carrying out workshops and calibrations for these analyses on a triennial basis since 2002 (i.e. WKFATHOM) and results show these calibrations are necessary.  

The analyses in step 1 is actually the same as for the histological validation of the maturity stage in maturity events. At the moment in the maturity events we haven’t a possibility to annotate the histological images. I think it would help in explanation for the maturity readers to actually be able to point out the different cell types explaining why a gonad is in a certain maturity stage.

o	Are the results used in the stock assessment process?
Not directly yet, we are in the process of estimating the effect of each error on the SSB estimate and how to incorporate the errors in the SSB index, similar to the AEM approach.

o	Do you know what groups deal with Fecundity and Atresia? (this is for possible linkage with WGBIOP) 
WGMEGS, WGACEGG, WGALES, and there is more EPMs carried out in the GFCM areas.

o	When would the module need to be developed (have the vague idea that next event was by November 2021 but was not 100% sure)
Next workshop is in November 2021 WKAEPM

o	Could WGSMART get information on the WK that they want to use it for?  (I think it was for a specific species but maybe it was related to a project or a stock assessment group).
Mackerel and horse mackerel, WKAEPM resolutions are in the WGBIOP 2020 report

**Comment by cmspinto** [comment]
For a clear evaluation of the issue and priority it would help WGSMART to know:
o	A short description on what specifically the module of “Fecundity and Atresia” is for and how will that contribute to improving the quality of data?

 **

> Reply: For egg production methods (EPM) to estimate spawning stock biomass (SSB) it is necessary to know the realised/batch fecundity. Egg production is divided by fecundity to calculate SSB. For mackerel, horse mackerel, anchovy and sardine EPM indices are used in the assessment. To estimate realised fecundity we first need to estimate potential or batch fecundity. This can only be estimated for fish close to or during spawning. Therefor ovaries are first screened histologically to get the true maturity stage (analyses 1). Then (batch) fecundity is estimated from whole mounts (analyses 2). During the spawning season fecundity is regulated by atresia. Thus atresia is estimated from histological samples (step 3). Lastly the spawning fraction, actual number of females that spawn in a day is estimated from histological slides by staging Post Ovulatory Follicles (POFs; step 4). We have been carrying out workshops and calibrations for these analyses on a triennial basis since 2002 (i.e. WKFATHOM) and results show these calibrations are necessary.
> 
> The analyses in step 1 is actually the same as for the histological validation of the maturity stage in maturity events. At the moment in the maturity events we haven’t a possibility to annotate the histological images. I think it would help in explanation for the maturity readers to actually be able to point out the different cell types explaining why a gonad is in a certain maturity

** 



o	Are the results used in the stock assessment process?

> **Reply: Not directly yet, we are in the process of estimating the effect of each error on the SSB estimate and how to incorporate the errors in the SSB index, similar to the AEM approach.**

o	Do you know what groups deal with Fecundity and Atresia? (this is for possible linkage with WGBIOP) 

> **WGMEGS, WGACEGG, WGALES, and there is more EPMs carried out in the GFCM areas.**

o	When would the module need to be developed (have the vague idea that next event was by November 2021 but was not 100% sure)

> **Next workshop is in November 2021 WKAEPM**

o	Could WGSMART get information on the WK that they want to use it for?  (I think it was for a specific species but maybe it was related to a project or a stock assessment group).

> **Mackerel and horse mackerel, WKAEPM resolutions are in the WGBIOP 2020 report**

**Comment by cmspinto** [comment]
We have had the idea to use Geoserver to stream the images to the client, we have done the first try and here it is an example:
http://geodata.ices.dk/geoserver/SQL/wms?service=WMS&version=1.1.0&request=GetMap&layers=SQL%3Asmartdots&bbox=-0.5%2C-0.5%2C1359.5%2C1022.5&width=768&height=577&srs=EPSG%3A404000&format=application/openlayers


@CindyvanDamme:  We need real images to make a test event and develop the module, I will drop an email to Anders and Cristina

**Comment by cmspinto** [comment]
@PeriklisICES has put an example in ArcGIS to make a test, example is available here: https://gis.ices.dk/gis/rest/services/TestFolder/SmartDots_full/MapServer?f=jsapi

**Comment by CindyvanDamme** [comment]
The geoserver image is bad quality for me when viewing. The PeriklisICES gives me a good quality image for viewing, however it takes seconds to load the image, and again when zooming and again when moving around in the image. Is there a possibility to download the image, or is it only sharing?

**Comment by PeriklisICES** [comment]
I have now enabled cache for 5 levels of zoom. That should improve loading time. If more zoom levels are required I could probably add them.

**Comment by CindyvanDamme** [comment]
Much quicker loading times now. We need to discuss the zoom levels needed with Anders and Maria

**Comment by cmspinto** [comment]
Create a new type of Annotation POF staging:
![image](https://user-images.githubusercontent.com/8705477/127992389-5e70bc00-dbdb-4ceb-ba09-d982f1c4aef0.png)


The event manager needs to be able to select the staging scale for:
- POF staging
- Atresia
- Histology screening

**Comment by cmspinto** [comment]
All annotations:
- Put the description in the toolbox



Fecundity:
- 185 Microns is the minimum size of the oocyte
- change the icons of the fecundity markers

**Comment by cmspinto** [comment]
Event is now running and we are waiting for the feedback.

**Comment by kbekaert** [comment]
Did we receive any feedback? Can we close this issue?
