### ISSUE TITLE
Link to Demo returns 404

### ISSUE THREAD

**Issue by pedlino** [ices-eg/SmartDots#227]
The link for the Demo environment
https://webapi.smartfisheries.be/api/demo
returns "No webpage was found for the web address" in a Chrome based browser (Vivaldi) and no error at all in Firefox.

**Comment by kevinatilvo** [comment]
Hi @pedlino, your browser isn't lying ;)
That's because it isn't a website, even if it may seem that way. It is a REST api (also using the http protocol).
The SmartDots software knows how to handle it. You need to enter it on the login screen.
![image](https://user-images.githubusercontent.com/25780423/112053569-cbf0c600-8b54-11eb-8581-74b15a3632e3.png)

However at the moment, when you try to login, you will receive a message that you need version 2.3. This version is not live yet, but should be coming within 1 week. If you want to try it out, let me know, I will send you a download link.

**Comment by pedlino** [comment]
Hi @kevinatilvo
I did not notice the information on the screenshot...
So there are two separate instances of Smartdot, one at ices.dk and another at smartfisheries.be?
Yes, I would like to try it out. Any bugs/features to look for?

Anyway, you can close this issue as Notabug ;)

**Comment by kevinatilvo** [comment]
@pedlino
There is only 1 software but there are multiple api's to connect to. These api's can tell the software how to behave to some extend.
For example the demo api settings can be found [here](https://webapi.smartfisheries.be/api/demo/getsettings) and the settings for ices will look differently.
There are in fact more than 2 implementations, but these 2 are the only ones I know of that are available on the internet.
There are 2 others that I know of that are intranet only, used by ILVO and WMR.

Here is the link to the portable (non installable) latest version (valid for 1 week):
https://wetransfer.com/downloads/c72eb75f519661a946c2af4dda588e2620210322214118/97d3cdb6077fa3bf90da0b3151301bd120210322214135/a752d0

unzip and run the SmartDots(.bat) file

This release is very minor as only [this](https://github.com/ices-eg/SmartDots/issues/170) issue was handled. The feature was requested by WMR and will not affect the ICES implementation.

**Comment by pedlino** [comment]
@kevinatilvo
Thank you for the explanation!
Downloaded version 2.3p and run on both addresses. It works perfectly. I can not test the bug since I can not Approve any Annotations :)
Thanks!
