### ISSUE TITLE
Startup of system at latest annotation

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#235]
If the system started up where you left off reading that would be convenient, instead of trying to find the last image you annotated 
Thanks guys for all your work with this
(Selene Hoey)

**Comment by wimallegaert** [comment]
Indeed, the available property 'no of annotations' should solve this. The condition therefore is that the value for “#Annotations” for all files must be correct when the file list data are sent to the software. Now, the fixed reading line from the event manager is counted as an annotation. When the image is selected the “#Annotations” property is corrected. I thought that bug was fixed in the past?

Alternative solutions: change the default order of the  file list in Web API. OrderBy  NumberOfAnnotations ASC ThenBy SampleNumber.

**Comment by JaneGodiksen** [comment]
Sometimes the reading line is counting as an annotation. Sometimes the green/red does not work properly.

**Comment by JCoadDavies** [comment]
There appears to be a bug which maybe event specific. Julie to comment more here

**Comment by wimallegaert** [comment]
related to #260

**Comment by JCoadDavies** [comment]
Tested on event 2020 Irish Sea Herring (EventID:268).  For the reader the colour indication worked fine as did the count of number of annotations (the pinned line was not included in the count).
For the event coordinator the pinned line was not included in the count of number of annotations BUT the count only appears once the file is chosen in the files panel.

**Comment by JCoadDavies** [comment]
Julie will test with another event on Sept 1st

**Comment by JCoadDavies** [comment]
Tested again in event ID450 and the same happened as with event ID268

**Comment by kbekaert** [comment]
Number of annotations is not loaded when the event is first opened (tested with event 457 and 456). @cmspinto bug fixing needed.
