### ISSUE TITLE
Software interface - image rotation

### ISSUE THREAD

**Issue by JaneGodiksen** [ices-eg/SmartDots#285]
It would be nice to have the facility to rotate images on Smartdots. (When doing the last Horse mackerel image exchange many of the uploaded images were orientated differently to the way some of the readers read them normally.)
Helen McCormic

**Comment by JaneGodiksen** [comment]
Can be done in the software easily. But if it needs to stay rotated, and stored like this in the database, then it is much more work.
Wim will have a look at what makes most sense regarding measurements etc.

**Comment by JaneGodiksen** [comment]
Milestone Q4 for checking possibilities

**Comment by wimallegaert** [comment]
The simplest solution is to include orientation instructions in the image guidelines. Optionally, extra functionality could be added to the web app so that images can be rotated before the start of an event.

Allowing images to be rotated by the user in the software is more complex as the rotation must be tracked and all coordinates must be calculated over and over again.

**Comment by cmspinto** [comment]
A quick question, this rotation is temporary? So the user is rotating only to have another perspective, but the image will not be saved like that?

**Comment by JCoadDavies** [comment]
Orientation instructions were included in the image guidelines.
