### ISSUE TITLE
We need uniform quality scores for all biological parameters in Smartdots (age, maturity, eggs and larvae).

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#308]
Development of generic quality scores.

**Comment by pcrjoana** [comment]
Did WGBIOP approve the changes to the quality scores? Before we implement them in our vocabulary, we will need to have WGBIOP's approval.

RMG agreed that we will implement the new "QS" codes in MeasurementCertainty and we will let the AQ codes live on. This because there is a change in concept between the current "AQ" codes and the new "QS" codes. and it wouldn't be correct to simply change the description.

**Comment by JCoadDavies** [comment]
Does the whole procedure of having to make a "ProcessForManagementOfChangesToReferenceData" document need to completed (as in 2020)?

**Comment by pcrjoana** [comment]
> Does the whole procedure of having to make a "ProcessForManagementOfChangesToReferenceData" document need to completed (as in 2020)?

No. :-) I already put it as an issue in RMG and we already started talking about this.
One thing I forgot to mention is that we'll be linking the old codes to the new ones. :-)

**Comment by kbekaert** [comment]
I sent a mail to Ingeborg Deboois from Datras to ask if they have input. I'm waiting for a reply. Then we can finalize it and send to WGBIOP for approval. It is kind of a long process with much people involved with all a different opinion :-). I'll keep you posted.
