### ISSUE TITLE
Planning of training sessions for the new modules.

### ISSUE THREAD

**Issue by kbekaert** [ices-eg/SmartDots#310]

**Comment by JCoadDavies** [comment]
[Subgroup work 25th Oct.docx](https://github.com/ices-eg/SmartDots/files/10085448/Subgroup.work.25th.Oct.docx)

**Comment by JCoadDavies** [comment]
Subgroup work 25th Oct updated and renamed with comments

[Notes on planning for new training session 2023.docx](https://github.com/ices-eg/SmartDots/files/10102657/Notes.on.planning.for.new.training.session.2023.docx)


Plan is 29-30 March 2023 - 4 hrs each day 
In preparation:
- Do we need a project deadline extension? maybe the training could be done in April instead of before the deadline.
- YouTube tutorials need to be updated in advance of training sessions https://github.com/ices-eg/SmartDots/issues/311 
- communication with ICES and advertisement of training session, participant list compiled and invitations sent
- need material in advance for the each module so that participants can upload samples
- Julie, Karen and Cindy to run the 3 individual sessions and Julie can run through the report if no-one else volunteers

**Comment by CindyvanDamme** [comment]
Age and Maturity done on 15-16 May 2023
Eggs and Larvae planned for 9th November
