### ISSUE TITLE
Enable column filter option to the files panel of the age reading module

### ISSUE THREAD

**Issue by JCoadDavies** [ices-eg/SmartDots#330]
As in the maturity and egg and larvae modules

**Comment by wimallegaert** [comment]
additional info from Fiona:
Improving ability to filter for various criteria (in the ‘File’ and ‘Annotations’ section of both the ageing and maturity modules so that we maximise SmartDots as a reference resource post exchange/workshop (and additionally as a training resource) - see attached document in email from Fiona on May 12

**Comment by kbekaert** [comment]
@wimallegaert, is it possible to tackle this issue together with the developments from ILVO/Ifremer?
